version: "3.3"

services:
  front:
    container_name: bani-front
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      - HOST=0.0.0.0
    volumes:
      - ./front:/app
    ports:
      - 4000:4000
    # command: bash -c "npm install && npm run dev"
networks:
  default:
    driver: bridge