import Vue from 'vue'
import Element from 'element-ui'
import locale from 'element-ui/lib/locale/lang/en'

import {
	// Pagination,
	Dialog,
	// Autocomplete,
	// Dropdown,
	// DropdownMenu,
	// DropdownItem,
	// Menu,
	// Submenu,
	// MenuItem,
	// MenuItemGroup,
	Input,
	// InputNumber,
	Radio,
	RadioGroup,
	RadioButton,
	Checkbox,
	// CheckboxButton,
	// CheckboxGroup,
	// Switch,
	// Select,
	// Option,
	// OptionGroup,
	Button,
	ButtonGroup,
	// Table,
	// TableColumn,
	// DatePicker,
	// TimeSelect,
	// TimePicker,
	// Popover,
	// Tooltip,
	// Breadcrumb,
	// BreadcrumbItem,
	// Form,
	// FormItem,
	// Tabs,
	// TabPane,
	// Tag,
	// Tree,
	// Alert,
	// Slider,
	// Icon,
	// Row,
	// Col,
	// Upload,
	Progress,
	// Spinner,
	// Badge,
	// Card,
	// Rate,
	// Steps,
	// Step,
	Carousel,
	CarouselItem,
	// Collapse,
	// CollapseItem,
	// Cascader,
	// ColorPicker,
	// Transfer,
	// Container,
	// Header,
	// Aside,
	// Main,
	// Footer,
	// Timeline,
	// TimelineItem,
	// Link,
	// Divider,
	// Image,
	// Calendar,
	// Backtop,
	// PageHeader,
	// CascaderPanel,
	// Loading,
	// MessageBox,
	// Message,
	// Notification
} from 'element-ui'

Vue.use({ locale })
// Components that are registered globaly.
const components = [
	Dialog,
	// Carousel,
	// CarouselItem,
	Button,
	ButtonGroup,
	Radio,
	RadioGroup,
	RadioButton,
	Progress,
	Input,
	Checkbox,
]

components.forEach(Component => {
	Vue.component(Component.name, Component)
})